### ISSUE TITLE
Cant run the app on my android phone

### ISSUE THREAD

**Issue by Ujjwalsharma2210** [freeCodeCamp/mobile#934]
**This is the error**
```
Invalid depfile: /Users/ujjwalsharma/code/github/freeCodeCampMobile/mobile-app/.dart_tool/flutter_build/0e009611283bdb702949b9dd5e9838c7/kernel_snapshot.d
Invalid depfile: /Users/ujjwalsharma/code/github/freeCodeCampMobile/mobile-app/.dart_tool/flutter_build/0e009611283bdb702949b9dd5e9838c7/kernel_snapshot.d
Error: Couldn't resolve the package 'stacked_core' in 'package:stacked_core/stacked_core.dart'.
lib/app/app.locator.dart:10:8: Error: Not found: 'package:stacked_core/stacked_core.dart'
import 'package:stacked_core/stacked_core.dart';
       ^
lib/app/app.locator.dart:31:27: Error: Type 'EnvironmentFilter' not found.
    {String? environment, EnvironmentFilter? environmentFilter}) async {
                          ^^^^^^^^^^^^^^^^^
lib/app/app.locator.dart:28:17: Error: Undefined name 'StackedLocator'.
final locator = StackedLocator.instance;
                ^^^^^^^^^^^^^^
lib/app/app.locator.dart:31:27: Error: 'EnvironmentFilter' isn't a type.
    {String? environment, EnvironmentFilter? environmentFilter}) async {
                          ^^^^^^^^^^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/getter.dart:7:52: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
  DateTime dateTime(DateTime dateTime) => dateTime.copyWith();
                                                   ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:73:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:84:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:95:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:106:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:117:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:128:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:141:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:152:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:163:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:181:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:192:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:203:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:214:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:225:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:236:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:252:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:268:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:279:32: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        newDateTime = dateTime.copyWith(
                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/manipulator.dart:307:21: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
    return dateTime.copyWith(
                    ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/parser.dart:23:12: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
          .copyWith(isUtc: isUtc);
           ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/parser.dart:27:48: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
      return _parseString(input, 'yyyy-MM-dd').copyWith(isUtc: isUtc);
                                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/parser.dart:29:48: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
      return _parseString(input, 'yyyy/MM/dd').copyWith(isUtc: isUtc);
                                               ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/parser.dart:32:36: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
      return DateTime.parse(input).copyWith(isUtc: isUtc);
                                   ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/parser.dart:54:10: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        .copyWith(isUtc: isUtc);
         ^^^^^^^^
../../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/jiffy-6.1.0/lib/src/parser.dart:70:10: Error: The method 'copyWith' isn't defined for the class 'DateTime'.
 - 'DateTime' is from 'dart:core'.
Try correcting the name to the name of an existing method, or defining a method named 'copyWith'.
        .copyWith(isUtc: isUtc);
         ^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Astacked_core%2Fstacked_core.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:659:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:799:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:625:9)
<asynchronous suspension>
#4      starter (package:frontend_server/frontend_server.dart:1451:12)
<asynchronous suspension>
#5      main (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:10:14)
<asynchronous suspension>



FAILURE: Build failed with an exception.

* Where:
Script '/Users/ujjwalsharma/Developer/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/ujjwalsharma/Developer/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
```
**Smartphone:**
 - Device: Redmi k20 pro
 - OS: android 11

Can someone tell me what is this. And a possible solution.

**Comment by Nirajn2311** [comment]
What's the flutter version and Android SDK you're using?

**Comment by Ujjwalsharma2210** [comment]
@Nirajn2311 ,
Flutter Version : 
Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (4 months ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

SDK version for android : 
compileSdkVersion 33

minSdkVersion 21
targetSdkVersion 31

**Comment by Nirajn2311** [comment]
Did you run `flutter pub get` before trying to build the app?

**Comment by Ujjwalsharma2210** [comment]
Yes, @Nirajn2311 I did flutter pub get.

**Comment by Nirajn2311** [comment]
Could you try starting fresh ie. deleting the project locally and recloning the fork. Also it would be better if you format the error stacktrace in a code block. For example
```
This is a code block
```
